graph TB
    %% Entidades
    PACIENTE[PACIENTE]
    MEDICO[MÉDICO]
    ENFERMEIRO[ENFERMEIRO]
    DEPARTAMENTO[DEPARTAMENTO]
    ESPECIALIDADE[ESPECIALIDADE]
    LEITO[LEITO]
    AGENDAMENTO[AGENDAMENTO]
    TIPO_AGENDAMENTO[TIPO AGENDAMENTO]
    PROCEDIMENTO[PROCEDIMENTO]
    INTERNACAO[INTERNAÇÃO]
    FATURAMENTO[FATURAMENTO]
    FATURA_ITEM[FATURA ITEM]
    HISTORICO[HISTÓRICO MÉDICO]
    EXAME[EXAME]
    TIPO_EXAME[TIPO EXAME]
    LABORATORIO[LABORATÓRIO]
    
    %% Relacionamentos
    PACIENTE ---|1:N realiza| AGENDAMENTO
    MEDICO ---|1:N atende| AGENDAMENTO
    LEITO ---|1:N utiliza| AGENDAMENTO
    TIPO_AGENDAMENTO ---|1:N classifica| AGENDAMENTO
    
    AGENDAMENTO ---|1:N possui| PROCEDIMENTO
    
    PACIENTE ---|1:N possui| INTERNACAO
    LEITO ---|1:N ocupa| INTERNACAO
    
    PACIENTE ---|1:N gera| FATURAMENTO
    FATURAMENTO ---|1:N contém| FATURA_ITEM
    
    PACIENTE ---|1:N possui| HISTORICO
    MEDICO ---|1:N registra| HISTORICO
    
    PACIENTE ---|1:N realiza| EXAME
    LABORATORIO ---|1:N executa| EXAME
    TIPO_EXAME ---|1:N classifica| EXAME
    LABORATORIO ---|1:N oferece| TIPO_EXAME
    
    ESPECIALIDADE ---|1:N possui| MEDICO
    DEPARTAMENTO ---|1:N aloca| MEDICO
    DEPARTAMENTO ---|1:N aloca| ENFERMEIRO
    
