graph TB
    %% Entidades
    PACIENTE[PACIENTE]
    MEDICO[MÉDICO]
    ENFERMEIRO[ENFERMEIRO]
    DEPARTAMENTO[DEPARTAMENTO]
    ESPECIALIDADE[ESPECIALIDADE]
    LEITO[LEITO]
    AGENDAMENTO[AGENDAMENTO]
    TIPO_AGENDAMENTO[TIPO AGENDAMENTO]
    PROCEDIMENTO[PROCEDIMENTO]
    INTERNACAO[INTERNAÇÃO]
    FATURAMENTO[FATURAMENTO]
    FATURA_ITEM[FATURA ITEM]
    HISTORICO[HISTÓRICO MÉDICO]
    EXAME[EXAME]
    TIPO_EXAME[TIPO EXAME]
    LABORATORIO[LABORATÓRIO]
    
    %% Relacionamentos
    PACIENTE ---|realiza| AGENDAMENTO
    MEDICO ---|atende| AGENDAMENTO
    LEITO ---|utiliza| AGENDAMENTO
    TIPO_AGENDAMENTO ---|classifica| AGENDAMENTO
    
    AGENDAMENTO ---|possui| PROCEDIMENTO
    
    PACIENTE ---|possui| INTERNACAO
    LEITO ---|ocupa| INTERNACAO
    
    PACIENTE ---|gera| FATURAMENTO
    FATURAMENTO ---|contém| FATURA_ITEM
    
    PACIENTE ---|possui| HISTORICO
    MEDICO ---|registra| HISTORICO
    
    PACIENTE ---|realiza| EXAME
    LABORATORIO ---|executa| EXAME
    TIPO_EXAME ---|classifica| EXAME
    LABORATORIO ---|oferece| TIPO_EXAME
    
    ESPECIALIDADE ---|possui| MEDICO
    DEPARTAMENTO ---|aloca| MEDICO
    DEPARTAMENTO ---|aloca| ENFERMEIRO